### ISSUE TITLE
Error loading images: Project __ not found

### ISSUE THREAD

**Issue by BorjaEst** [grycap/im-dashboard#33]
Hi,

I get the following error on the field "Select Site image: " when deploying a VM:
```
Error loading site images: Project eosc-synergy.eu not found!
```
![Screenshot from 2020-06-02 10-12-51](https://user-images.githubusercontent.com/47473455/83496617-a6a5a500-a4b9-11ea-955c-10c17665b867.png)

After checking with @mariojmdavid, it seems the name configured for the project was "eosc-synergy" not "eosc-synergy.eu".

I supose a way to solve it would be to change the project name on OpenStack, however it looks this is not always possible.

Would it be an alternative to fix this issue?

**Comment by BorjaEst** [comment]
Probably that is much better aproach.

Before closing the issue,  AppDB images are not displayed any longer in some sites. Might it be related?
![image](https://user-images.githubusercontent.com/47473455/85830354-bba9e700-b78c-11ea-9264-19cca3b7da9e.png)

**Comment by micafer** [comment]
Dear @BorjaEst ,

In this case the problem is that some sites (CESNET, IFCA, LIP, ...) does not download and publish the AppDB images.
In this case you have to select the images from the other select field "Select Site image". In this dropdown list you will get the list of OpenStack images available.
